spring:
    application:
        name: bjmh-cloud-system
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/bjmh?useUnicode=true&characterEncoding=UTF8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
    basepackage: com.bjmh.cloud.system.*.mapper
    xmlLocation: classpath:mapper/*.xml
server:
  port: 8860
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/